# Generated by Django 3.2.4 on 2021-06-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ediarists_adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarist',
            name='postal_code',
            field=models.CharField(max_length=8),
        ),
    ]
