# Generated by Django 3.2.4 on 2021-06-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ediarists_adm', '0002_alter_diarist_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarist',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
